stages:
  - build
  - test

image: gradle:7.3.3-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

buildServer:
  stage: build
  script:
    - ./gradlew :server:build -x checkStyleMain -x compileTestJava -x processTestResources -x testClasses -x checkstyleTest -x check
  artifacts:
    untracked: true
    expire_in: 1 hour

buildCommons:
  stage: build
  script:
    - ./gradlew :commons:compileJava
  artifacts:
    untracked: true
    expire_in: 1 hour

buildClient:
  stage: build
  script:
    - ./gradlew :client:build -x checkStyleMain -x compileTestJava -x processTestResources -x testClasses -x checkstyleTest -x check
  artifacts:
    untracked: true
    expire_in: 1 hour

testServerRun:
  stage: test
  needs:
    - buildServer
  dependencies:
    - buildServer
  script:
    - printf 'command="./gradlew bootRun"\nlog="run.log"\nsuccessMatch="JVM running for"\nerrorMatch="Exception:\|Error:\|Caused By"\n$command > "$log" 2>&1 &\npid=$!\nwhile sleep 3\ndo\nif grep -q "$errorMatch" "$log"\nthen\nkill $pid\nexit 1\nfi\nif grep -F -q "$successMatch" "$log"\nthen\nkill $pid\nexit 0\nfi\ndone\n' > script.sh
    - chmod +x ./script.sh
    - ./script.sh

testCheckStyleCommons:
  stage: test
  needs:
    - buildCommons
  dependencies:
    - buildCommons
  script:
    - ./gradlew :commons:checkStyleMain  -x compileJava -x classes -x processResources -x jar

testCheckStyleServer:
  stage: test
  needs:
    - buildServer
  dependencies:
    - buildServer
  script:
    - ./gradlew :server:checkStyleMain -x compileJava -x classes -x processResources -x jar

testCheckStyleClient:
  stage: test
  needs:
    - buildClient
  dependencies:
    - buildClient
  script:
    - ./gradlew :client:checkStyleMain -x compileJava -x classes -x processResources -x jar


testAndCoverage:
  stage: test
  needs:
    - buildClient
    - buildServer
    - buildCommons
  dependencies:
    - buildClient
    - buildServer
    - buildCommons
  script:
    - ./gradlew test -x compileJava -x classes -x processResources -x jar
    - ./gradlew AggregateJacocoReport -x compileJava -x classes -x processResources -x jar
    # preserve coverage information in an easy-to-reach folder
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    name: "Test reports from $CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - "*/build/test-results/test/TEST-*.xml"
      - "./coverage"
    reports:
      junit:
        - "*/build/test-results/test/TEST-*.xml"
  coverage: /TestCoverage:(\d+)%/

